[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x", "openssl"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "pnpm i --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm --filter @modele/types build",
  "pnpm --filter @modele/web build"
]

[start]
cmd = "pnpm --filter @modele/web start"

